# WhatATheme
markdown: kramdown

# URL of the Site
url: "https://felixrodrigo19.github.io"
baseurl: ""

# Title of the Site
title: Rodrigo's Portfolio
# Description of the Site
description: |
  Experienced Python developer adept at building APIs and conducting web scraping using Scrapy framework and 
  Requests libraries within an agile team environment. Actively involved in the development of new products 
  leveraging Spring Boot and several AWS services. Passionate about learning new technologies and methodologies 
  to enhance code quality and foster collaborative team performance.
# URL of Image of the Site
# Keywords of the Site
site-keywords: Python, Developer, Backend Engineer, Backend Software Engineer
# URL for the Image of custom Favicon
favicon-url: assets/images/favicon.ico
perfil: assets/images/perfil.jfif

name: Rodrigo dos Santos Felix
  
# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
#heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: felixs.rodrigo@gmail.com
linkedin_username: rodrigosfelix
github_username: felixrodrigo19

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
